import type { LeaderboardEntry, Signal, Challenge } from '../types'

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    id: '1',
    user_id: 'u1',
    sfide_totali: 145,
    vittorie: 112,
    sconfitte: 33,
    win_rate: 77.2,
    pips_totali: 4820,
    streak_attuale: 8,
    rank: 1,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u1', email: 'null@htt.io', username: 'null_trader', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '2',
    user_id: 'u2',
    sfide_totali: 98,
    vittorie: 71,
    sconfitte: 27,
    win_rate: 72.4,
    pips_totali: 3650,
    streak_attuale: 5,
    rank: 2,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u2', email: 'hack@htt.io', username: 'hack_master', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '3',
    user_id: 'u3',
    sfide_totali: 87,
    vittorie: 61,
    sconfitte: 26,
    win_rate: 70.1,
    pips_totali: 3120,
    streak_attuale: 3,
    rank: 3,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u3', email: 'x@htt.io', username: 'xterm_bull', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '4',
    user_id: 'u4',
    sfide_totali: 76,
    vittorie: 52,
    sconfitte: 24,
    win_rate: 68.4,
    pips_totali: 2890,
    streak_attuale: 2,
    rank: 4,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u4', email: 'ghost@htt.io', username: 'ghost_pip', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '5',
    user_id: 'u5',
    sfide_totali: 65,
    vittorie: 43,
    sconfitte: 22,
    win_rate: 66.2,
    pips_totali: 2340,
    streak_attuale: 1,
    rank: 5,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u5', email: 'byte@htt.io', username: 'byte_trader', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '6',
    user_id: 'u6',
    sfide_totali: 54,
    vittorie: 34,
    sconfitte: 20,
    win_rate: 63.0,
    pips_totali: 1980,
    streak_attuale: 0,
    rank: 6,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u6', email: 'crypto@htt.io', username: 'crypto_zero', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '7',
    user_id: 'u7',
    sfide_totali: 48,
    vittorie: 29,
    sconfitte: 19,
    win_rate: 60.4,
    pips_totali: 1650,
    streak_attuale: 0,
    rank: 7,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u7', email: 'dark@htt.io', username: 'dark_forex', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '8',
    user_id: 'u8',
    sfide_totali: 41,
    vittorie: 24,
    sconfitte: 17,
    win_rate: 58.5,
    pips_totali: 1420,
    streak_attuale: 0,
    rank: 8,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u8', email: 'net@htt.io', username: 'net_scalper', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '9',
    user_id: 'u9',
    sfide_totali: 35,
    vittorie: 20,
    sconfitte: 15,
    win_rate: 57.1,
    pips_totali: 1180,
    streak_attuale: 0,
    rank: 9,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u9', email: 'red@htt.io', username: 'red_candle', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: '10',
    user_id: 'u10',
    sfide_totali: 28,
    vittorie: 15,
    sconfitte: 13,
    win_rate: 53.6,
    pips_totali: 890,
    streak_attuale: 0,
    rank: 10,
    periodo: 'alltime',
    updated_at: new Date().toISOString(),
    users: { id: 'u10', email: 'sys@htt.io', username: 'sys_breaker', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  }
]

export const mockSignals: Signal[] = [
  {
    id: 's1',
    user_id: 'u1',
    asset: 'EUR/USD',
    direzione: 'BUY',
    entry_min: 1.0850,
    entry_max: 1.0870,
    tp1: 1.0920,
    tp2: 1.0970,
    tp3: 1.1020,
    sl: 1.0800,
    timeframe: 'H4',
    status: 'open',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    users: { id: 'u1', email: '', username: 'null_trader', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: 's2',
    user_id: 'u2',
    asset: 'GBP/USD',
    direzione: 'SELL',
    entry_min: 1.2650,
    entry_max: 1.2670,
    tp1: 1.2580,
    tp2: 1.2530,
    tp3: 1.2480,
    sl: 1.2720,
    timeframe: 'H1',
    status: 'win',
    pips_result: 70,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    users: { id: 'u2', email: '', username: 'hack_master', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: 's3',
    user_id: 'u3',
    asset: 'BTC/USD',
    direzione: 'BUY',
    entry_min: 67200,
    entry_max: 67500,
    tp1: 68500,
    tp2: 69000,
    tp3: 70000,
    sl: 66500,
    timeframe: 'D1',
    status: 'open',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    users: { id: 'u3', email: '', username: 'xterm_bull', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: 's4',
    user_id: 'u1',
    asset: 'GOLD',
    direzione: 'BUY',
    entry_min: 2320,
    entry_max: 2330,
    tp1: 2360,
    tp2: 2390,
    tp3: 2420,
    sl: 2295,
    timeframe: 'H4',
    status: 'open',
    created_at: new Date(Date.now() - 900000).toISOString(),
    users: { id: 'u1', email: '', username: 'null_trader', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: 's5',
    user_id: 'u4',
    asset: 'US30',
    direzione: 'SELL',
    entry_min: 38800,
    entry_max: 38850,
    tp1: 38600,
    tp2: 38400,
    tp3: 38200,
    sl: 39000,
    timeframe: 'H1',
    status: 'loss',
    pips_result: -200,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    users: { id: 'u4', email: '', username: 'ghost_pip', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  }
]

export const mockChallenges: Challenge[] = [
  {
    id: 'c1',
    tipo: '1v1',
    challenger_id: 'u1',
    opponent_id: 'u2',
    asset: 'EUR/USD',
    durata_ore: 24,
    stato: 'active',
    challenger_pips: 85,
    opponent_pips: 62,
    inizio: new Date(Date.now() - 3600000 * 12).toISOString(),
    fine: new Date(Date.now() + 3600000 * 12).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    challenger: { id: 'u1', email: '', username: 'null_trader', avatrade_verified: true, ruolo: 'trader', created_at: '' },
    opponent: { id: 'u2', email: '', username: 'hack_master', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: 'c2',
    tipo: '1v1',
    challenger_id: 'u3',
    opponent_id: 'u4',
    asset: 'GBP/USD',
    durata_ore: 48,
    stato: 'active',
    challenger_pips: 120,
    opponent_pips: 135,
    inizio: new Date(Date.now() - 3600000 * 24).toISOString(),
    fine: new Date(Date.now() + 3600000 * 24).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    challenger: { id: 'u3', email: '', username: 'xterm_bull', avatrade_verified: true, ruolo: 'trader', created_at: '' },
    opponent: { id: 'u4', email: '', username: 'ghost_pip', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  },
  {
    id: 'c3',
    tipo: '1v1',
    challenger_id: 'u5',
    opponent_id: undefined,
    asset: 'GOLD',
    durata_ore: 72,
    stato: 'pending',
    challenger_pips: 0,
    opponent_pips: 0,
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    challenger: { id: 'u5', email: '', username: 'byte_trader', avatrade_verified: true, ruolo: 'trader', created_at: '' }
  }
]
